name: Update .mjs to .js

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rename .mjs to .js and replace in files
        run: |
          find . -name "*.mjs" -not -path "./.git/*" -not -path "./.github/*" -exec bash -c 'mv "$0" "${0%.mjs}.js"' {} \;
          find . -type f -not -path "./.git/*" -not -path "./.github/*" -exec sed -i 's/\.mjs/\.js/g' {} +

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Convert .mjs files to .js" || echo "No changes to commit"
          git push
